[package]
name = "pollen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
druid = {git = "https://github.com/linebender/druid.git"}

[net]
git-fetch-with-cli = true